### ISSUE TITLE
Show drivers their accepted rides in UI

### ISSUE THREAD

**Issue by aliceduongg** [aliceduongg/StuberProject#13]
Description: The accepted rides will be displayed below the available rides section, making it easy for drivers to see both their current commitments and new opportunities.

Tasks:
  - Add a new API endpoint for fetching driver-specific accepted rides
  - Show a separate section for accepted rides in the driver's dashboard
  - Style accepted rides differently from available rides
  - Display all relevant ride information for accepted rides
  - Keep the existing functionality for available rides

**Comment by JoePan001** [comment]
Please check the ridestest branch.
I added some codes in rides.js to fetch the users so that only the specific user can see the rides. For drivers, the function works fine, but for the rider, they can't see the rides they booked.
No error message in console
I am using the same fetching codes for both riders and drivers in rides.js and dashboard.tsx
Which is pretty hard to debug

**Comment by aliceduongg** [comment]
Tested functionality (done), it works well.
